server:
  port: 8081
spring:
  application:
    name: "Solicitudes"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  cache:
    type: caffeine
    cache-names:
      - statuses
      - loan_types
    caffeine:
      # CORREGIDO: Se ajusta el tiempo de expiración a 1 hora (3600s)
      spec: maximumSize=500,expireAfterAccess=500s
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "crediya"
    schema: "solicitudes"
    username: "postgres"
    password: "P1o2s3G4."
  restconsumer:
    url: "http://localhost:8080/api/v1/usuarios"
  user-api:
    timeout: 5000
    url: "http://localhost:8080"
resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"

# Propiedades de negocio externalizadas
app:
  rules:
    client-role-id: 2
    pending-status-id: 1
    # Asegúrate de que esta sección exista y esté bien indentada
    terminal-status-ids: [ 2, 3, 4 ] # 2=APROBADO, 3=RECHAZADO, 4=CANCELADO

logging:
  config: classpath:log4j2-spring.xml
