server:
  port: 8081 # Usa la variable de entorno, o 8081 por defecto para local
spring:
  application:
    name: "Solicitudes"

  # --- Configuración de Base de Datos Estándar de Spring Boot ---
  # Spring Boot usará esta sección para auto-configurar la conexión.
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/crediya
    username: ${DB_USER}
    password: ${DB_SECRET}
    properties:
      schema: solicitudes
    pool:
      enabled: true
      initial-size: 5
      max-size: 10
      max-idle-time: 30m
      connect-timeout: 5s

  # Conexión JDBC para migraciones (Flyway/Liquibase)
  #datasource:
  #  url: jdbc:postgresql://localhost:5432/crediya
  #  username: ${DB_USER}
  #  password: ${DB_SECRET}

  devtools:
    add-properties: false

  profiles:
    include: null
  cache:
    type: caffeine
    cache-names:
      - statuses
      - loan_types
    caffeine:
      spec: maximumSize=500,expireAfterAccess=500s
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
  tracing:
    sampling:
      probability: 1.0 # Captura el 100% de las trazas en desarrollo
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

adapters:
  restconsumer:
    url: "http://localhost:8080/api/v1/usuarios"
  user-api:
    timeout: 5000
    url: "http://localhost:8080"

resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"

# Propiedades de negocio externalizadas
app:
  rules:
    client-role-id: 3
    pending-status-id: 1
    terminal-status-ids: [ 2, 3, 4 ] # 2=APROBADO, 3=RECHAZADO, 4=CANCELADO

logging:
  config: classpath:profiles/web-service.yaml

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000 # 1 hour in milliseconds